app = "bef-schools-comparison"
primary_region = "iad"

[build]

[http_service]
  internal_port = 5040
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[env]
  FLASK_ENV = "production"
