// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHxFQ75xw3h6Tf_nAgiIG7oq5kHzcDgvQ',
    appId: '1:827719336372:web:24e15d8506f67a89f232e1',
    messagingSenderId: '827719336372',
    projectId: 'befverification',
    authDomain: 'befverification.firebaseapp.com',
    storageBucket: 'befverification.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMuHCE7dJyj-UlgVUQyqc5rw6pMsVjH7M',
    appId: '1:827719336372:android:b7866d9df3f6d16bf232e1',
    messagingSenderId: '827719336372',
    projectId: 'befverification',
    storageBucket: 'befverification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4hKifbi6T0fG_K9nzz7VQSPdlnRg_dOU',
    appId: '1:827719336372:ios:35af07a003780685f232e1',
    messagingSenderId: '827719336372',
    projectId: 'befverification',
    storageBucket: 'befverification.firebasestorage.app',
    iosBundleId: 'com.example.befVerification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4hKifbi6T0fG_K9nzz7VQSPdlnRg_dOU',
    appId: '1:827719336372:ios:35af07a003780685f232e1',
    messagingSenderId: '827719336372',
    projectId: 'befverification',
    storageBucket: 'befverification.firebasestorage.app',
    iosBundleId: 'com.example.befVerification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHxFQ75xw3h6Tf_nAgiIG7oq5kHzcDgvQ',
    appId: '1:827719336372:web:35d71bef31fd3dd7f232e1',
    messagingSenderId: '827719336372',
    projectId: 'befverification',
    authDomain: 'befverification.firebaseapp.com',
    storageBucket: 'befverification.firebasestorage.app',
  );
}
